name = "PackFramework 1.18.2"
author = "Den4enko"
version = "v2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ded93983a63eb9a690621cd50032b765787f9962dda647516fdb24533d10b2e4"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"
