name = "PackFramework 1.18.2"
author = "Den4enko"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "960b9eb5dc8479ea067eb3ec2775ef8a0b5afbe5e675a699593e1e725b26ae63"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"
