name = "PackFramework"
author = "Den4enko"
version = "35"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17790cf6d900b851859c95ec90ef81f599ef6153d95c79eb924e864ff79697e1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"

[options]
no-internal-hashes = true
