name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v19.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ee132f0a54b21429b68f8b6929d62bef1e36db2cf877e59fa77f2f8aaf4b9ac"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
