name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "161bde86fdcb698f817597348d2d656828051aa7ef879845775c02f372e76e9d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
