name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v8.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e036cff22f0d884373549850f69576fc55ae1b7bd301d95e3ec45daa4cf5d68a"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
