name = "PackFramework"
author = "Den4enko"
version = "2.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4b7cc9d89a0143b8d617afad5604cbbbff27f9e263fa8dd3cba4f84de50a581"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
