name = "PackFramework"
author = "Den4enko"
version = "2.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26303ed409ee821a518261acb6a7805f6282b38aa7b14b5bf07e47d8590043fc"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
