name = "PackFramework"
author = "Den4enko"
version = "2.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ba606403853e6df2e56a4ee331d29d986cf80c751061c1002a6d842bcd8df41"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
