name = "PackFramework"
author = "Den4enko"
version = "2.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "246c00dfe41eb00ed6e482b05cb284f4c412e81b529ce16854c1189ec568955b"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
