name = "PackFramework"
author = "Den4enko"
version = "2.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2e806c6a16da558674c4d36965afc1ae5eadb54fc359bf3de218ca526cfc7e8"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
