name = "ForgePackBase"
author = "Den4enko"
version = "2.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ebd3c36cd5c2ec1b81db338350c2471d2c0da1d52d11995194f04f2854f1679"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
