name = "PackFramework"
author = "Den4enko"
version = "2.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab41733b4c3de21120e994488899307a7e79bd970d242ba5f2babf091f36ba96"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
