name = "ForgePackBase"
author = "Den4enko"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a23f1173755e75c9f2a2af3ef9de66daab9d5289792922a87d167e2cd0c7cd3a"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
