name = "ForgePackBase"
author = "Den4enko"
version = "1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2bdd938e5f8ed6665fd3836934b2ca4fe953207fa1c94f6f77a56529b5b33f5"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
