name = "PackFramework"
author = "Den4enko"
version = "2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d09e533651e972a1a6dbf816201a9b8f6381b307237d050507ce7ee7585407ff"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
