name = "PackFramework"
author = "Den4enko"
version = "2.5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1002fa3e571976147a9abaff1fdfab7e0e93c7a5fa68d50f601feecc64ed712f"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
