name = "ForgePackBase"
author = "Den4enko"
version = "2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "315a85383f042ac712abd324a2fb8f78f7b8747a692ea9c69dbf761778b5fa6f"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
