name = "PackFramework"
author = "Den4enko"
version = "2.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16dec204971adfc576195ed5985a93b0294502d6e1c3d860ec525189d9aed8ec"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
