name = "PackFramework"
author = "Den4enko"
version = "2.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aae8a6af68e775d9d9cbe1135853894748b34239bd3657975b9f74d85195d6b"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
