name = "PackFramework"
author = "Den4enko"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f120799c11a39639b54b90c0aa365466b93289ec00e0af3d522454d7ad01eb8"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
