name = "PackFramework"
author = "Den4enko"
version = "2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "105174ac7d790af991daad10475e2939ca8ef6007163f130a97594e614721ca8"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
