name = "ForgePackBase"
author = "Den4enko"
version = "2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e51b10c0f1db4ae5d8e369168d7f19b88bea851493f08b0af408fa579845a5ff"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
