name = "ForgePackBase"
author = "Den4enko"
version = "1.11.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51358fff741f62f42410780736b048e8303129d77bae72552d0159c2c36b1f8a"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
