name = "PackFramework"
author = "Den4enko"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b887b1a983a0d2a6fba00f23f816a06bcdbd5f9207e72e73138176652338de56"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
