name = "ForgePackBase"
author = "Den4enko"
version = "1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa0aeed67d05ba006dd1950a32aeb6f413d67b7d867008bfc643421786e2953a"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
