name = "ForgePackBase"
author = "Den4enko"
version = "2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d328a16479246aa07c998a9cab03ee32ef717a79fcafa7bd20872ed08d69a2b8"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
