name = "ForgePackBase"
author = "Den4enko"
version = "2.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "befefe131dde5a82481e05e56f4ad679bed488b84c5b15559996086b1e565f2f"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
