name = "PackFramework"
author = "Den4enko"
version = "2.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88dfb30adb7e816118780c9d755ce230498bd7b84383bb02d5292c5eb1716b07"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
