name = "ForgePackBase"
author = "Den4enko"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04ea5dff6cf70047bc4d4dc017efcfad36e34990572f7214869788f459755a60"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
