name = "ForgePackBase"
author = "Den4enko"
version = "1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66ba194d5ac77cd12d6ce6666cd9e2e03a76d9c6325cd5c22ba1c9802e30cf75"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
