name = "ForgePackBase"
author = "Den4enko"
version = "2.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "267bd2a2b9c894aae2ec77172f29a92caad5a5ff6f3b70cbd0a8ada7c32cc95f"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
