name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "575a406ef73e96befe6d5142dae80ec740f805409d3f4d293bedaf7a9cee6565"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
