name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "686de757756094c3e4bf6a8528e348f764aad468ce320340cffd27ac0f95e21a"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
