name = "PackFramework 1.21.1"
author = "Den4enko"
version = "v31.b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb7cbb7cb39ba182996d6c52276479a8265ce7bfb63c64ed766142f34f00136b"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
