name = "PackFramework 1.20.1"
author = "Den4enko"
version = "3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "320c7eac0dffa23e63fab43808f6d5274c9cc6f641bed119d42a59b3a9a846b0"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.102"
