name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4d4329bc3de654463044a05b45f2434c6790ce62d38099c786985fec55b0e49"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
