name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bccec595e5aa1fe2c5c8e12f2d8395752385bd12e8aedc668f98792c92fd5868"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
