name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8e3724178fe0d2cc24855139261caa2ba8f2ade433c3a67955daeaa5b8a2936"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
