name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e67647e36c7ac6262aa79c38932ebba7af18de3da5bd3887660a9fa8bba0d7c"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
