name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b9051b4314cbcdbaa8d4f0497c42e17d254c8342c9be8366dd01667109a7791"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
