name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a72d51f19641ea5724856a972c3a5890a31a3bf068de02163d64241d24211cac"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
