name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6cea3cb0cacdecd9e4545e62f5f740d3c92dbccaac384956df1880fafe4349d"

[versions]
forge = "47.3.27"
minecraft = "1.20.1"
