name = "PackFramework 1.19.2"
author = "Den4enko"
version = "2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04d1efcb7a83961318a288b5f5fb247cbeb3430e4884db11b3deeb4edb22528e"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
