name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e875e815253f033eb25c733bfad9e1db4f47acdba2a0c6c886fc959afc3ff76"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
