name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66b8ca4d6c750be2f4deed31b5f7a4b577e1a981183573ad01705da940ff1cef"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
