name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7769eb0f8e3131a81c6104015f6995fe713ca298cd5e4f694870e22a769ebbb"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
