name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f244e0f3968ca88b88b9e97465ce25fcbc2368491133d59a93b8045f7687611"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
