name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e49376d1bc3a0be3e37b5607721f423ad05e202b3152942e4a9479182ad478e"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
