name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bb55e6d8d20b12a7f71acf54e25eb3164072c280df23f153859aa950e332008"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
