name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9b7f3bf247ff49f090b87919ba8b9577aeaa51c371b1af51372ccd37ec71041"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
