name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f274f8ab3a575cb4a03c87e80ad2aa48a6f797553963c6073606598ff683285"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
