name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v4-b1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2e712c6f2f0354fda7e09e390c8aa9a90883eb55d4c768533a90144dd0ee69b"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
