name = "PackFramework"
author = "Den4enko"
version = "34"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d6e478ec67693e017b393a64374c8450a3371ac10e2398c4b6a15d7bdb11e00"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"

[options]
no-internal-hashes = true
