name = "PackFramework"
author = "Den4enko"
version = "35"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab9441982aa370e32771d19374c372d14d6f1baa5e9e9bf378539e1f990e3685"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"

[options]
no-internal-hashes = true
