name = "PackFramework"
author = "Den4enko"
version = "34"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "238b4486653d4b30286ffbc9461ecb363605d46df8a407d4264474d3032282bd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"

[options]
no-internal-hashes = true
