name = "PackFramework"
author = "Den4enko"
version = "35"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0de4353e0be211ce1c93a6252bb16bfb17ed40af16d45192008e64b1d9b5618"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"

[options]
no-internal-hashes = true
