name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "266b401b145a18592cf87f287757eeb500b401953ddb4ac61264cc565eb0fed0"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
