name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v8.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d5d6041dbfe0bae803843c7a47b2084d180b65125a1474371bee8df5bd0d69f"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
