name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbe79deffe8b531305ae97bdf2aede5a001fdcd8e05fa8c8fd9077758d115496"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
