name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e6b6755fefc98a6591bf095ec04688e309d3a8e2f103f0428dac0efef5eaa3f"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
