name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17a7a8df63a5a1da16947c7a8e3174107cb3c1fd2e9c26194c64724958575b67"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
