name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v31.b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b9ced67e5323856cc075298820a8f3bf3707e2634ac8099fc11c40b18dceaa4"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
