name = "PackFramework"
author = "Den4enko"
version = "dev-20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8d5ad4b300106b30258df2766238d6d9479ea2a2e530f10db35c0aeae85c656"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"

[options]
no-internal-hashes = true
