name = "PackFramework"
author = "Den4enko"
version = "dev-10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e470d09b1d43ac551f7548ece0d3a23a8a194e490fb90ba3e665507a4744d68"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
no-internal-hashes = true
