name = "PackFramework"
author = "Den4enko"
version = "dev-12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afa45f3cd8c8fdc9338868085db54f7bb246eb4a26eeeb0fd0fe3bb37639ddf9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
no-internal-hashes = true
