name = "PackFramework 1.18.2"
author = "Den4enko"
version = "v2-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0679dc9cfac0f31d22584e34dfc247537d49106509bc31a287f99cf3a5b1593"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"
