name = "PackFramework 1.18.2"
author = "Den4enko"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "359f2c508f37dd0512d042ee2555c84e37abf3d22297b6924155bdda968e2bab"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"
