name = "PackFramework"
author = "Den4enko"
version = "v38.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09b57126e63bdc3946c7f45e085d626ca65e8b4ff4e5cdd98145edfbb97e606c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
no-internal-hashes = true
