name = "PackFramework 1.21.1"
author = "Den4enko"
version = "v31.b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e81a900b3dc769e26c1055ff5fbad8ae0459107e86f2b7017c8baa81f42fe50"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.210"
