name = "PackFramework 1.21.1"
author = "Den4enko"
version = "v31.b1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f6243daa30768def3bb79df31e0bd7ce71b72550e1fa37b0f0acb278555d1fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.210"
