name = "PackFramework"
author = "Den4enko"
version = "dev-17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d6e822de54c330b7148628ab5eebbabce6e06471f4d6d2363924276018ae073"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"

[options]
no-internal-hashes = true
