name = "PackFramework"
author = "Den4enko"
version = "dev-12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e124aef5cbfc7b299f1e7b93ece26d25dfe3e13538c0f166c699db62c296f27"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
no-internal-hashes = true
