name = "PackFramework 1.18.2"
author = "Den4enko"
version = "noVersion"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = ""

[versions]
forge = "40.2.18"
minecraft = "1.18.2"
