name = "PackFramework 1.19.2"
author = "Den4enko"
version = "noVersion"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = ""

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
