name = "PackFramework 1.21.1"
author = "Den4enko"
version = "v31.b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cd614f040581269baf79979fbafaf5bd631f78ff9ae000e4fc9b1c0bc159644"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
