name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v3.b8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7ae29d2e2f0e77672d49abefc3c4e5028c20d39a89ddb87634b36302bd8c755"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
