name = "PackFramework 1.21.1"
author = "Den4enko"
version = "noVersion"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = ""

[versions]
neoforge = "21.1.212"
minecraft = "1.21.1"
