name = "PackFramework"
author = "Den4enko"
version = "v38.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e35a3f92523cfa78493416c8547b5611057ed80200478374879479c61159062a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
no-internal-hashes = true
