name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v31.b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaaab052bbd06e1f4f4496ee813a3ed3452235060201ff983915a69775bf3821"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
