name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a6da79c5c8b23b9b55a4805f1946d575745005edffb632cd4a62951531502af"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
