name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1c16496cc2c86d792fc0bc8dc0b5e2d8396ba72db320388263c6784555a4211"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
