name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fbc599e35fd81faef546cb25d41c44d3296c885caba28e11934e985cda3b11a"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
