name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4c2df4ce6c987baa90fedc4e509d0d1d5584b01b3623409e1297e030509e383"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
