name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82b18dbd38e36f7e57c3c54e729e6c0ec18ac8ead1f6ce478451f7066d00dc66"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
