name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v19.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e755e5ecdb2ffca2b403f6d175ec9508fe4deb653977c4cf833fd6ae806af37"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
