name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v2-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b282c4c99d811f128f6cf19108db791676ace5fd270679453123e7407f21a28"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
