name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v3.b6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0b1642a152c60e15f9be54a2eeeedcc8369f3f6577bad2098c25a02b87253bb"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.1"
