name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v2-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd29ad3fef6b77da27912cde206c885ffd1c1af191d23e1df0b2815695340b38"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
