name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v3.b6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e11e23974524be127758a3ffc435c30d8b156741d0f22308160241edbd3e94ae"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
