name = "PackFramework 1.19.2"
author = "Den4enko"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f15f9d32e302fcd4bd130b9813e6dbb917434ce29e6fa7264a2059d7f909a95"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
