name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v2.b01"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c42f607ce864bfd97b90e8fe2dbef0e85aa951844b6b4007fb9d5a43eeb976dd"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
