name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v3.b01"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15b00f3fc5d7b749e5ed4c54ab4b587a22a890286faf6a0f56fe737147bc32a2"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
