name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v2.b05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0831472efa22ac9777fcff20c6692908f837408301572db8d8ac8d75eed691eb"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
