name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f59cc66329784d1f460132a5684c5db10b3690f7a9822c2f5d028b054cd92442"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
