name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v2-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bba2f588c6141a8b504f89c5fe368a1dd72d5ebd25349c4edc946f1c45a114d"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
