name = "PackFramework 1.19.2"
author = "Den4enko"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "168014aec6f6ccc168590dff5029ee43eecf4b011e20fe0da367fdc92a8398c6"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
