name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b81272f53dfbe1cf6c8b72d1c3df0b65e9bd14f68e95163ed8f0ec9f3cb41f3"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
