name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v3.b7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68348f32df01298ffde30a8cdbf4b6a3ef9c0be01e218fe014bb0045f89d3a12"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
