name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v3.b8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b049f9180096cabbea312b54565118802e0899ac8ffeaf1441cf604d8389ae97"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
