name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3eb1282fa8b5e15bdf6e25518cfc37a68c4e63c8968331e1f8e8511b517558e"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
