name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82037cf39314cbfcef5201cabc57272eaa464787f8cc085cab4f8d3710a5fc64"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
