name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v31.b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa0a217c1c00b650340d69d017d10800dcb2196436007258c55ec6f8cf393616"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
