name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8234419171715edc0fd3d78705fde46aec25aa98b878e3f99937572da906c241"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
