name = "PackFramework"
author = "Den4enko"
version = "dev-20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56bb6234d4ba1db1cea9bcece8746e6efefa565fbf7df75dfa490f620a20cd0e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"

[options]
no-internal-hashes = true
