name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v31.b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ceada5f9f84abfe3033c578029f2fe14a30881b359dbdcdfaac1a6d87c1315e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
