name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v31.b1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "292f73b9ae3ee33f5c388b1c1851a12b8b3e5d4dc5e6d4bab8509745235b718e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
