name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v23"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d197b913071feebb2de2f528926de0bacadc6ea18dbc13dbc3dc163397fdbafe"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
