name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f088115e0388a2923265ffd007b8f6b6b9e36dd972608be0ce15cbeb62abb0e8"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
