name = "PackFramework 1.20.1"
author = "Den4enko"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e8d87410c5ea1a77225cd163cfacbc17a799fc3b9c0717892dd00166ca13dbf"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
