name = "PackFramework 1.19.2"
author = "Den4enko"
version = "v2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a527fb8026018b24de802ac38d3fe79335045555052ac3d9927ab9ef966bb30d"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
