name = "PackFramework 1.19.2"
author = "Den4enko"
version = "2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ad2a615246455e31e81ba10752671b8997d60be804e37e8ae5ae73fabdff87a"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"
