name = "PackFramework 1.18.2"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a434b5dbfedaf2dcdf9a2a3bd6a7ac56d5aff94530f1b1070e550b22160a5b4"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"
