name = "PackFramework 1.18.2"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a62292d9d0964f85b3bc39ecbee895d9399edd059b14fafd51b4b45c490264e6"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"
