name = "PackFramework 1.18.2"
author = "Den4enko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d75fabfbd04773784d5266e7d70c6c5d4b9d02a0e21fdd4830272f03742fa5d4"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"
