name = "PackFramework 1.21.1"
author = "Den4enko"
version = "v31.b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf6c8c5a6550ed2c0af79ffaaa5fac7db6e6af391b1c2281c020758370f49d27"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
