name = "PackFramework 1.18.2"
author = "Den4enko"
version = "v3.b4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee17c2569eeadcf1f3e6bfb197b931f5cefa1f34929f687af815f2c121b99dd2"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
