name = "PackFramework 1.18.2"
author = "Den4enko"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40767016eed6bf545e46779ba4a79e53a4e91f157358c23fc1033ec168347d9b"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"
