name = "PackFramework 1.18.2"
author = "Den4enko"
version = "v3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77eacc7295db42f4aa372905a3d3f13e432688df7b813ea2cdc5ee1a4b190dca"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
