name = "PackFramework 1.18.2"
author = "Den4enko"
version = "v3.b8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "091e0e2ea124d00d6a167e30d760a3490e6c1fd03e22061dd168529529ed6951"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
