name: Copy folder from one branch to another

on:
  push:
    branches: [ main ]  # Replace with the source branch name

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.push.branches[0] }}  # Get the source branch name

      - name: Copy folder
        run: |
          git checkout main
          cd ..
          cp -r PackFramework/beta release
          rm -rf PackFramework/*
          cp -r release/ PackFramework
          cd PackFramework
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      - name: Push changes to target branch
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release  # Replace with the target branch name
          force: true
